---
title: "Resources for Closed Community Modeling Competitions"
author: "Adam Gilbert and Sarah Dumnich"
format: html
theme: flatly
toc: true
---

This page points out to resources associated with the eCOTS Posters and Beyond presentation titled *In-Class Modeling Competitions and Language Models for Data Generation* by Adam Gilbert (Southern New Hampshire University) and Sarah Dumnich (Saint Vincent College). You can see our slide deck below, and here's a link to the five minute video presentation (link to be added).

<center>

<iframe class="slide-deck" src="eCOTS_SlideDeck.html" width="50%" height="250"></iframe>

</center>

## Creating a Kaggle Competition

We've had good success using Kaggle as a hosting platform for my modeling competitions. Follow [this link](https://agmath.github.io/eCOTSmodelingComps/HostingKaggleCompetitions.html){target="_blank"} for instructions on how to set up your own *Community Competition* on Kaggle. We'll show you how to make your competition closed so that only individuals you invite are able to join. Note that these instructions reference the *data generation* script which is [described and linked below](#data-gen).

## Assignments for Semester-Long Competitions

With semester-long competitions, Adam gives a series of about six assignments to walk students through the data analysis and modeling process. You can see sample assignments below. You should feel free to use or adapt them to suit your needs.

1. [Competition Assignment 1](https://agmath.github.io/ClassificationCourse/CA1.html){target="_blank"}: *joining the competition and reading in your data*
2. [Competition Assignment 2](https://agmath.github.io/ClassificationCourse/CA2.html){target="_blank"}: *Statement of Purpose and Exploratory Data Analysis*
3. [Competition Assignment 3](https://agmath.github.io/ClassificationCourse/CA3.html){target="_blank"}: *a first model, model assessment, predictions, and writing about Model Construction and Interpretation*
4. [Competition Assignment 4](https://agmath.github.io/ClassificationCourse/CA4.html){target="_blank"}: *additional models, model tuning, and more predictions*
5. [Competition Assignment 5](https://agmath.github.io/ClassificationCourse/CA5.html){target="_blank"} (if appropriate): *utilizing text-based features*
6. [Competition Assignment 6](https://agmath.github.io/ClassificationCourse/CA6.html){target="_blank"} (if appropriate): *constructing and utilizing deep learning models, summarizing results in a Conclusions section*

Through these assignments, students get practice writing about their analysis and modeling processes, exploring data, constructing models, assessing their performance, and utilizing the models to make predictions on new observations with unknown responses. Students also get feedback on their work, especially on the narration throughout the partial report they are constructing. This is helpful since their final course project is to write a complete analytics report using a data set of their choosing.

## Using Language Models as Data Generation Assistants

We've use language models to help us create novel data sets in the past. Follow [this link](https://agmath.github.io/eCOTSmodelingComps/LLM_DataGen.html){target="_blank"} to learn more about *why* we've done that and *how* we made it happen.

## Generating and Splitting Data{#data-gen}

When hosting your own Kaggle Competition, you'll need to obtain or generate several data sets. In particular, participants will need training data, a competition data set (with a missing response variable), and a sample submission file. You'll also need to supply Kaggle with an answer key so that submissions from participants can be scored and ranked.

Here's a [link to a sample data generation and splitting script](https://github.com/agmath/eCOTSmodelingComps/blob/main/BarbequeComp_DataGen.r){target="_blank"}.

## Anecdotes and Student Feedback

While we haven't conducted any formal analyses on these competition assignments, we have made the following observations:

+ Students are motivated to engage with the modeling process even between assignments because they are driven to win the competition. Statistical modeling has become like an academic e-Sport in courses where we've utilized competitions.
+ Students are thinking about the mathematics behind their models, especially when those models take a long time to tune or fit.
+ Students are thinking about the differences between model performance metrics. For example, "my model had a very high cross-validation *accuracy*, but why didn't that translate into a low *log-loss* score in the competition?"
+ Especially in short competitions, students are thinking more carefully about the model hyperparameters they are choosing to tune, whether tuning multiple hyperparameters is "worth it", and which hyperparameters they'd like to prioritize tuning.
+ Some students make heavy use of residual analyses and try to understand where and why their models perform most poorly. Of these students, many "invent" the notion of an ensemble of models far before they are introduced in class. Anecdotally, this preliminary self-discovery has made the notion of ensembles of models more intuitive to these students.
+ The one-day competitions are viewed by the students as fun ways to test out their knowledge. They really enjoyed the low stakes and immediate reward of seeing the winner.
+ The semester-long competition was viewed more as a learning opportunity. So while still motivating, less fun and exciting.
+ Having six assignments might be too many, depending on what other assignments are due towards the end of the semester.
+ Student feedback suggested having informal presentations to discuss their strategies with the class.

## Check Out a Competition!

We've built and released a competition that runs the week of eCOTS 2024. The competition opens on June 10 and closes at 11:59pm on June 14. We've made the competition *private* so that you can see how this would work if you built a similar competition. Because it is private, the competition is not discoverable via search on Kaggle -- it is only accessible via the direct link below.

The competition uses our synthetic barbeque dataset, and your goal is to predict the number of units of propane used at each of 7,500 barbeques and you have 22,500 barbeques to train on. [You can access (and join) the competition here](https://www.kaggle.com/t/c80bfae88f5e4b818743c61f065507ad) and feel free to join and submit your own model predictions if you'd like!
